server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mylearn
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 10
        min-idle: 2


mybatis:
  mapper-locations: /mapper/*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

